#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## Drop privileges and run help-steps/sign-and-tag.
## signing-key-create refuses to run as root.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

target_user=builder

cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")/../.."

./help-steps/run-as-user --chown /work -- "${target_user}" ./help-steps/sign-and-tag
