---
name: Build Raw (arm64)

on:
  workflow_call:
    inputs:
      build_group:
        required: true
        type: string
      distro:
        required: true
        type: string
      flavor:
        required: true
        type: string
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      use_remote_repo:
        required: false
        type: boolean
        default: false

jobs:
  build-raw-arm64:
    if: >-
      contains(fromJSON('["all", "raw-all", "whonix-all", "kicksecure-all"]'), inputs.build_group)
      || (inputs.build_group == 'custom'
          && contains(fromJSON('["all", "raw"]'), inputs.target)
          && contains(fromJSON('["all", "arm64"]'), inputs.arch))
    strategy:
      fail-fast: false
      matrix:
        distro: [whonix, kicksecure]
        flavor: [lxqt, cli]
        exclude:
          - distro: ${{ (inputs.build_group == 'whonix-all' || (inputs.build_group == 'custom' && inputs.distro == 'kicksecure')) && 'whonix' || 'NONE' }}
          - distro: ${{ (inputs.build_group == 'kicksecure-all' || (inputs.build_group == 'custom' && inputs.distro == 'whonix')) && 'kicksecure' || 'NONE' }}
          - flavor: ${{ (inputs.build_group == 'custom' && inputs.flavor == 'cli') && 'lxqt' || 'NONE' }}
          - flavor: ${{ (inputs.build_group == 'custom' && inputs.flavor == 'lxqt') && 'cli' || 'NONE' }}
    uses: ./.github/workflows/build.yml
    with:
      distro: ${{ matrix.distro }}
      flavor: ${{ matrix.flavor }}
      target: raw
      arch: arm64
      runner: ubuntu-24.04-arm
      use_remote_repo: ${{ inputs.use_remote_repo }}
