---
name: Build ISO (amd64)

on:
  workflow_call:
    inputs:
      build_group:
        required: true
        type: string
      distro:
        required: true
        type: string
      flavor:
        required: true
        type: string
      target:
        required: true
        type: string
      arch:
        required: true
        type: string
      use_remote_repo:
        required: false
        type: boolean
        default: false

jobs:
  build-iso-amd64:
    if: >-
      contains(fromJSON('["all", "iso-all", "kicksecure-all"]'), inputs.build_group)
      || (inputs.build_group == 'custom'
          && contains(fromJSON('["all", "iso"]'), inputs.target)
          && contains(fromJSON('["all", "amd64"]'), inputs.arch)
          && contains(fromJSON('["all", "kicksecure"]'), inputs.distro))
    strategy:
      fail-fast: false
      matrix:
        flavor: [lxqt, cli]
        exclude:
          - flavor: ${{ (inputs.build_group == 'custom' && inputs.flavor == 'cli') && 'lxqt' || 'NONE' }}
          - flavor: ${{ (inputs.build_group == 'custom' && inputs.flavor == 'lxqt') && 'cli' || 'NONE' }}
    uses: ./.github/workflows/build.yml
    with:
      distro: kicksecure
      flavor: ${{ matrix.flavor }}
      target: iso
      arch: amd64
      runner: ubuntu-24.04
      use_remote_repo: ${{ inputs.use_remote_repo }}
